services:
  gallery:
    image: josiahdc/gallery:0.1
    build:
      context: .
    ports:
      - "36363:33333"
    env_file: "./gallery.env"
    environment:
      STORAGE_DIRECTORY: /atelier/storage
    volumes:
      - gallery-storage:/atelier/storage

volumes:
  gallery-storage:
    external: false
